#!/usr/bin/env bash

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

# Shortcuts
alias dots="cd ~/.dotfiles"
alias dv="cd ~/Devel"
alias devel="cd ~/Devel"
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag="--color"
#  export LS_COLORS='no=00:fi=00:di=01;31:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'
else # macOS `ls`
  colorflag="-lGH"
#  export LSCOLORS='BxBxhxDxfxhxhxhxhxcxcx'
fi

# Always use color output for `ls`
alias ls="ls ${colorflag}"

# List all files colorized in long format, including dot files
alias la="ls -laF ${colorflag}"

# List all files colorized in long format
alias ll="ls -lF ${colorflag}"

# List only directories
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Enable aliases to be sudo’ed
alias sudo='sudo '

# Get week number
alias week='date +%V'

# IP addresses
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Show active network interfaces
alias ifactive="ifconfig | pcregrep -M -o '^[^\t:]+:([^\n]|\n\t)*status: active'"

# Canonical hex dump; some systems have this symlinked
command -v hd > /dev/null || alias hd="hexdump -C"

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec ${SHELL} -l"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# git stuff
alias ga="git add "
alias gA="git add -A"
alias gb="git branch"
alias gbd="git branch -D"
alias gbs="git rev-parse --abbrev-ref HEAD"
alias gcm="git commit"
alias gcm_a="git commit --amend"
alias gco="git checkout"
alias gco_b="git checkout -b"
alias gco_d="git checkout develop"
alias gd="git diff"
alias gd_f="git diff --name-status"
alias gd_d="git diff develop --name-status"
alias gd_d_f="git diff develop -- $@"
alias gd_gh_m="git diff github/main --name-status"
alias gd_gh_m_f="git diff github/main -- $@"
alias gp_gh="git push github \$(git rev-parse --abbrev-ref HEAD)"
alias gp_gh_f="git push github +\$(git rev-parse --abbrev-ref HEAD)"
alias gd_m="git diff main --name-status"
alias gd_m_f="git diff main -- $@"
alias gd_od="git diff origin/develop --name-status"
alias gd_od_f="git diff origin/develop -- $@"
alias gd_om="git diff origin/main --name-status"
alias gd_om_f="git diff origin/main -- $@"
alias gl="git log"
alias gp="git pull"
alias gpo="git push -u origin \$(git rev-parse --abbrev-ref HEAD)"
alias gpo_f="git push -u origin +\$(git rev-parse --abbrev-ref HEAD)"
alias gpo_gh="git push -u github \$(git rev-parse --abbrev-ref HEAD)"
alias gpo_gh_f="git push -u github +\$(git rev-parse --abbrev-ref HEAD)"
alias gr_o="git pull ; git reset --hard origin ; git pull"
alias gr_od="git pull ; git reset --hard origin/develop"
alias gr_om="git pull ; git reset --hard origin/main"
alias grb="git rebase "
alias grb_d="git rebase origin/develop"
alias gs="git status"
alias gsm_u="git submodule update --recursive --remote"

pushsync () {
  BRANCH="$(git rev-parse --abbrev-ref HEAD)"
  MSG="${@:-Sync $BRANCH}"
  M="$(printf "$MSG\n\nFiles:\n$(for i in $(git diff HEAD --name-only); do echo "  - $i"; done)\n")"
  git commit -a -m "$M"
  git push
}

# neovim
alias vi='nvim'
alias vim='nvim'

# venv
alias venv=". **/bin/activate"
alias vdev="source ~/Devel/venv/bin/activate"

# misc
alias dus="find . -maxdepth 1 -type d -exec du -ch -d1 '{}' +"
alias dus_g="find . -maxdepth 1 -type d -exec du -ch -d1 '{}' + | grep -P '^[0-9]+(?:.[0-9]+)?G\s+.*$'"
